"""new fileds in user model

Revision ID: 906ec36df5d4
Revises: 6620812e95e5
Create Date: 2022-08-06 16:40:16.577505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906ec36df5d4'
down_revision = '6620812e95e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
